students = [
    'fardin', 
    'shafaith', 
    'rafi', 
    'humaira', 
    'owaji', 
    "Yoga mat",
    "Sunglasses",
    "Laptop bag",
    "Purse",
    "Travel bag",
    "Bracelet (gift from Mark)",
    "Cross bracelet",
    "Gray/white scarf",
    "Green scarf",
    "Black pashmina",
    "Casual hat",
    "Red Sox hat",
    "Winter hat",
    "Winter mittens",
    "Winter coat",
    "Winter vest",
    "Trench coat",
    "Leather jacket",
    "Black rain coat",
    "Blue hiking coat",
    "Robe",
    "Yoga pants",
    "Black undershirt/tank",
    "Black hiking/workout shorts",
    "Workout shorts",
    "Workout shirt",
    "Workout shirt",
    "Sweatshirt",
    "Bathing suit",
    "Bathing suit cover up",
    "Underwear (grouped)",
    "Lounge shirt",
    "Lounge shirt",
    "Lounge pants",
    "PJs (cool weather)",
    "Lingerie",
    "Lingerie",
    "Night gown",
    "Night gown",
    "Tank top PJs (warm weather)",
    "Purple heels",
    "Black flats",
    "Black boots",
    "Snow boots",
    "Hiking shoes",
    "Sport shoes",
    "Tennis shoes",
    "Flip-flops",
    "Jeans",
    "White dress capris",
    "Blue outdoors capris",
    "Dress pants",
    "Khaki pants",
    "Black skinny pants",
    "Black sleeveless dress",
    "Orange/white dress",
    "Green/white dress",
    "Blue sleeveless dress",
    "Holiday dress",
    "Gray maxi skirt/dress",
    "Gray short skirt",
    "Tweed skirt",
    "Black wrap short sleeve",
    "Black tank",
    "Yellow tank",
    "Black tank flower detail on back",
    "Gray ruffle shirt",
    "Plaid button down",
    "Light blue button down",
    "Black long-sleeved tissue tee",
    "Gray long-sleeved tissue tee",
    "Black cardigan",
    "Cream cardigan",
    "Black blazer",
    "Cream blazer",
    "White sweater",
    "Green sweater",
    "Laptop/charger",
    "Phone/charger",
    "Camera/charger",
    "External hard drive",
    "Rosetta Stone headphones",
    "Ear buds",
    "Photo card reader",
    "Office supplies (pens/pencils/paper/paperclips/files)",
    "Diary (planner/calendar)",
    "Bible",
    "Kindle + charger",
    "1 book in progress (+ small rotating library of less than 10 books)",
    "Toothbrush",
    "Hairbrush",
    "Blow dryer",
    "Flat-iron",
    "Makeup (grouped)",
    "Tennis dress",
    "Tennis racquet",
    "Journal",
    "Candle set (gift)",
    "Bike gear (grouped)",
    "Ski gear (grouped and stored until Winter)",
   
]




print(students[0])
print(students[1])
print(students[2])
print(students[3])



for student in students:
    print( student )



print(len (students))